pref("extensions.readalltweets.general.showRepliesToo", true);
pref("extensions.readalltweets.general.notifyDM", true);
pref("extensions.readalltweets.general.changeColorOfNewTweets", true);
pref("extensions.readalltweets.general.checkIntervalOfNewTweets", 3);
pref("extensions.readalltweets.general.lists", "");
pref("extensions.readalltweets.general.disableThisAddonTemporarily", false);
pref("extensions.readalltweets.general.LimitTheNumberOfFetchedTweets", false);
pref("extensions.readalltweets.general.showOnlyTheMostRecentTweets", false);
pref("extensions.readalltweets.general.maximumNumberOfFetchedTweets", 100);
pref("extensions.readalltweets.lastStatus", "{}");
pref("extensions.readalltweets.lastReply", "{}");
pref("extensions.readalltweets.lastDM", "{}");
pref("extensions.readalltweets.oauth", "{}");
pref("extensions.readalltweets.firstrun", true);
pref("extensions.readalltweets.configModified", false);

pref("extensions.readalltweets@masahal.info.name", "chrome://readalltweets/locale/strings.properties");
pref("extensions.readalltweets@masahal.info.description", "chrome://readalltweets/locale/strings.properties");
pref("extensions.readalltweets@masahal.info.translator", "chrome://readalltweets/locale/strings.properties");
